export const metadata = {
    title: "Not Found",
    description: "Generated by Next.js",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return <>{children}</>;
  }
  