import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../providers";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  const messages = useMessages();
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Providers>{children}</Providers>
          </NextIntlClientProvider>
        </body>
      </UserProvider>
    </html>
  );
}