import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Noto_Sans_Georgian } from "next/font/google";
import ThemeProviders from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const sans = Noto_Sans_Georgian({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = useMessages();
  return (
    <html lang="en">
      <UserProvider>
        <body className={sans.className}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <ThemeProviders>{children}</ThemeProviders>
          </NextIntlClientProvider>
        </body>
      </UserProvider>
    </html>
  );
}
